# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.

In [1]:
import pandas as pd
import numpy as np

## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

In [51]:
# Se estiver no Google Colab, descomente estas linhas:
# from google.colab import files
# uploaded = files.upload()

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

In [40]:
df.head(5)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [52]:
df.tail(5)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aluno        30 non-null     int64
 1   nome            30 non-null     object
 2   idade           28 non-null     float64
 3   turma           30 non-null     object
 4   curso           29 non-null     object
 5   nota1           28 non-null     float64
 6   nota2           27 non-null     float64
 7   faltas          28 non-null     float64
 8   cidade          29 non-null     object
 9   uf              29 non-null     object
 10  data_matricula  30 non-null     object
 11  mensalidade     29 non-null     float64
 12  bolsista        29 non-null     object
 13  email           28 non-null     object
 14  status          30 non-null     object
dtypes: float64(5), int64(1), object(9)
memory usage: 3.6+ KB

## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

In [43]:
df[['nome','curso','turma','nota1']]

              nome            curso turma  nota1
0        Ana Clara               IA     A    8.5
1       Bruno Lima  Desenvolvimento     A    6.0
2      Carla Souza               IA     B    9.2
3      Diego Alves            Dados     B    5.5
4     Eduarda Melo            Dados     A    7.8
5     Felipe Rocha               IA     C    4.0
6   Gabriela Nunes  Desenvolvimento     C    8.0
7   Henrique Silva               IA     A    NaN
8    Isabela Costa            Dados     B    9.5
9       João Pedro  Desenvolvimento     A    6.7
10      Karen Dias            Dados     B    7.0
11     Lucas Matos               IA     C    3.5
12    Mariana Reis            Dados     A    8.8
13   Nicolas Prado  Desenvolvimento     B    5.9
14  Olivia Martins               IA     C   10.0
15     Paulo Vitor            Dados     A    6.3
16   Quezia Araújo               IA     B    7.4
17    Rafael Gomes  Desenvolvimento     C    4.8
18   Sara Teixeira            Dados     A    7.9
19   Thiago Mendes               IA     C    5.0
20   Ursula Ferraz            Dados     B    8.1
21  Vinicius Lopes  Desenvolvimento     A    6.9
22   Wesley Castro               IA     B    2.5
23   Ximena Duarte            Dados     C    9.1
24    Yasmin Rocha               IA     A    8.3
25     Zeca Barros  Desenvolvimento     C    6.1
26       Ana Clara               IA     A    8.5
27   Beatriz Moura              NaN     B    7.2
28    Caio Moreira            Dados     C    NaN
29   Daniela Pires  Desenvolvimento     B    8.4

In [13]:
df_notas=df[['nome','nota1','nota2','faltas']]
df_notas

              nome  nota1  nota2  faltas
0        Ana Clara    8.5    9.0     2.0
1       Bruno Lima    6.0    7.5     5.0
2      Carla Souza    9.2    NaN     1.0
3      Diego Alves    5.5    6.0     8.0
4     Eduarda Melo    7.8    8.1     NaN
5     Felipe Rocha    4.0    5.5    12.0
6   Gabriela Nunes    8.0    8.8     0.0
7   Henrique Silva    NaN    7.9     3.0
8    Isabela Costa    9.5    9.7     1.0
9       João Pedro    6.7    6.2     4.0
10      Karen Dias    7.0    7.0     6.0
11     Lucas Matos    3.5    4.5    15.0
12    Mariana Reis    8.8    9.1     2.0
13   Nicolas Prado    5.9    6.8     7.0
14  Olivia Martins   10.0    9.8     0.0
15     Paulo Vitor    6.3    5.9     9.0
16   Quezia Araújo    7.4    8.2     2.0
17    Rafael Gomes    4.8    NaN    11.0
18   Sara Teixeira    7.9    8.0     3.0
19   Thiago Mendes    5.0    5.2    10.0
20   Ursula Ferraz    8.1    8.3     1.0
21  Vinicius Lopes    6.9    7.1     5.0
22   Wesley Castro    2.5    3.0    18.0
23   Ximena Duarte    9.1    9.0     0.0
24    Yasmin Rocha    8.3    8.7     2.0
25     Zeca Barros    6.1    5.8    14.0
26       Ana Clara    8.5    9.0     2.0
27   Beatriz Moura    7.2    7.6     4.0
28    Caio Moreira    NaN    NaN     NaN
29   Daniela Pires    8.4    8.9     1.0

## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

In [16]:
df[df['curso']=='IA']

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo

In [17]:
df[df['nota1'] >=7]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [21]:
df[(df['turma']=='B')&(df['curso']=='Dados')]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo

In [22]:
df[df['faltas']>5]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco

## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

In [53]:
df.isna().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             2
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

In [54]:
df[df['idade'].isna()]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo

In [55]:
df['nota1']=df['nota1'].fillna(df['nota1'].mean())
df.isna().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             0
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

In [71]:
df['bolsista']=df['bolsista'].str.lower()
df['bolsista']=df['bolsista'].replace({
    'não':'Não',
    'nao':'Não',
    'sim':'Sim'
})
df

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.000000,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.200000,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.500000,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.800000,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.000000,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.000000,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,7.032143,7.9,3.0,Formosa,GO,2025-02-05,850.0,Não,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.500000,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.700000,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.000000,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.500000,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.800000,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.900000,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.000000,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.300000,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.400000,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.800000,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.900000,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.000000,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.100000,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.900000,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.500000,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.100000,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.300000,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.100000,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.200000,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,7.032143,NaN,NaN,NaN,NaN,2025-02-22,780.0,Sim,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.400000,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo

In [69]:
df['uf']=df['uf'].str.upper()
df['uf']

0      DF
1      GO
2      DF
3      GO
4      DF
5      GO
6      DF
7      GO
8      DF
9      GO
10     DF
11     GO
12     DF
13     DF
14     DF
15     GO
16     DF
17     DF
18     DF
19     GO
20     DF
21     GO
22     DF
23     DF
24     DF
25     GO
26     DF
27     DF
28    NaN
29     DF
Name: uf, dtype: object

In [70]:
df['cidade']=df['cidade'].str.title()
df['cidade']

0                 Brasília
1                  Goiânia
2                 Brasília
3                 Anápolis
4               Taguatinga
5                 Luziânia
6                 Brasília
7                  Formosa
8                 Brasília
9     Aparecida De Goiânia
10                Brasília
11              Valparaíso
12                Brasília
13                    Gama
14                Brasília
15        Cidade Ocidental
16                Brasília
17              Planaltina
18              Sobradinho
19            Águas Lindas
20                Brasília
21                 Goiânia
22                Brasília
23              Taguatinga
24                Brasília
25                 Goiânia
26                Brasília
27                Brasília
28                     NaN
29                Brasília
Name: cidade, dtype: object

## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

In [76]:
df['media']= (df['nota1']+df['nota2'])/2
df

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
0,1,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.000000,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.750000
2,3,Carla Souza,19.0,B,IA,9.200000,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN
3,4,Diego Alves,NaN,B,Dados,5.500000,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.750000
4,5,Eduarda Melo,21.0,A,Dados,7.800000,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.950000
5,6,Felipe Rocha,22.0,C,IA,4.000000,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.750000
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.000000,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.400000
7,8,Henrique Silva,23.0,A,IA,7.032143,7.9,3.0,Formosa,GO,2025-02-05,850.0,Não,henrique.silva@email.com,Ativo,7.466071
8,9,Isabela Costa,20.0,B,Dados,9.500000,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.600000
9,10,João Pedro,19.0,A,Desenvolvimento,6.700000,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.450000
10,11,Karen Dias,24.0,B,Dados,7.000000,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.000000
11,12,Lucas Matos,18.0,C,IA,3.500000,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.000000
12,13,Mariana Reis,21.0,A,Dados,8.800000,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.950000
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.900000,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.350000
14,15,Olivia Martins,19.0,C,IA,10.000000,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.900000
15,16,Paulo Vitor,22.0,A,Dados,6.300000,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.100000
16,17,Quezia Araújo,23.0,B,IA,7.400000,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.800000
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.800000,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN
18,19,Sara Teixeira,18.0,A,Dados,7.900000,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.950000
19,20,Thiago Mendes,21.0,C,IA,5.000000,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.100000
20,21,Ursula Ferraz,22.0,B,Dados,8.100000,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.200000
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.900000,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.000000
22,23,Wesley Castro,20.0,B,IA,2.500000,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.750000
23,24,Ximena Duarte,21.0,C,Dados,9.100000,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.050000
24,25,Yasmin Rocha,NaN,A,IA,8.300000,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.500000
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.100000,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.950000
26,27,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000
27,28,Beatriz Moura,20.0,B,NaN,7.200000,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.400000
28,29,Caio Moreira,19.0,C,Dados,7.032143,NaN,NaN,NaN,NaN,2025-02-22,780.0,Sim,NaN,Ativo,NaN
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.400000,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo,8.650000

In [78]:
df['aprovado']=df['media']>=7
df

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado
0,1,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000,True
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.000000,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.750000,False
2,3,Carla Souza,19.0,B,IA,9.200000,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN,False
3,4,Diego Alves,NaN,B,Dados,5.500000,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.750000,False
4,5,Eduarda Melo,21.0,A,Dados,7.800000,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.950000,True
5,6,Felipe Rocha,22.0,C,IA,4.000000,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.750000,False
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.000000,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.400000,True
7,8,Henrique Silva,23.0,A,IA,7.032143,7.9,3.0,Formosa,GO,2025-02-05,850.0,Não,henrique.silva@email.com,Ativo,7.466071,True
8,9,Isabela Costa,20.0,B,Dados,9.500000,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.600000,True
9,10,João Pedro,19.0,A,Desenvolvimento,6.700000,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.450000,False
10,11,Karen Dias,24.0,B,Dados,7.000000,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.000000,True
11,12,Lucas Matos,18.0,C,IA,3.500000,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.000000,False
12,13,Mariana Reis,21.0,A,Dados,8.800000,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.950000,True
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.900000,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.350000,False
14,15,Olivia Martins,19.0,C,IA,10.000000,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.900000,True
15,16,Paulo Vitor,22.0,A,Dados,6.300000,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.100000,False
16,17,Quezia Araújo,23.0,B,IA,7.400000,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.800000,True
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.800000,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN,False
18,19,Sara Teixeira,18.0,A,Dados,7.900000,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.950000,True
19,20,Thiago Mendes,21.0,C,IA,5.000000,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.100000,False
20,21,Ursula Ferraz,22.0,B,Dados,8.100000,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.200000,True
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.900000,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.000000,True
22,23,Wesley Castro,20.0,B,IA,2.500000,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.750000,False
23,24,Ximena Duarte,21.0,C,Dados,9.100000,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.050000,True
24,25,Yasmin Rocha,NaN,A,IA,8.300000,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.500000,True
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.100000,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.950000,False
26,27,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000,True
27,28,Beatriz Moura,20.0,B,NaN,7.200000,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.400000,True
28,29,Caio Moreira,19.0,C,Dados,7.032143,NaN,NaN,NaN,NaN,2025-02-22,780.0,Sim,NaN,Ativo,NaN,False
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.400000,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo,8.650000,True

In [80]:
def classificar_faltas(f):
    if f> 10:
        return 'Alto risco'
    elif f>= 6:
        return 'Atenção'
    else:
        return 'Ok'

df['situacao_faltas'] = df['faltas'].apply(classificar_faltas)

df

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
0,1,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000,True,Ok
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.000000,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.750000,False,Ok
2,3,Carla Souza,19.0,B,IA,9.200000,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN,False,Ok
3,4,Diego Alves,NaN,B,Dados,5.500000,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.750000,False,Atenção
4,5,Eduarda Melo,21.0,A,Dados,7.800000,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.950000,True,Ok
5,6,Felipe Rocha,22.0,C,IA,4.000000,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.750000,False,Alto risco
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.000000,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.400000,True,Ok
7,8,Henrique Silva,23.0,A,IA,7.032143,7.9,3.0,Formosa,GO,2025-02-05,850.0,Não,henrique.silva@email.com,Ativo,7.466071,True,Ok
8,9,Isabela Costa,20.0,B,Dados,9.500000,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.600000,True,Ok
9,10,João Pedro,19.0,A,Desenvolvimento,6.700000,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.450000,False,Ok
10,11,Karen Dias,24.0,B,Dados,7.000000,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.000000,True,Atenção
11,12,Lucas Matos,18.0,C,IA,3.500000,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.000000,False,Alto risco
12,13,Mariana Reis,21.0,A,Dados,8.800000,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.950000,True,Ok
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.900000,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.350000,False,Atenção
14,15,Olivia Martins,19.0,C,IA,10.000000,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.900000,True,Ok
15,16,Paulo Vitor,22.0,A,Dados,6.300000,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.100000,False,Atenção
16,17,Quezia Araújo,23.0,B,IA,7.400000,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.800000,True,Ok
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.800000,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN,False,Alto risco
18,19,Sara Teixeira,18.0,A,Dados,7.900000,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.950000,True,Ok
19,20,Thiago Mendes,21.0,C,IA,5.000000,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.100000,False,Atenção
20,21,Ursula Ferraz,22.0,B,Dados,8.100000,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.200000,True,Ok
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.900000,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.000000,True,Ok
22,23,Wesley Castro,20.0,B,IA,2.500000,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.750000,False,Alto risco
23,24,Ximena Duarte,21.0,C,Dados,9.100000,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.050000,True,Ok
24,25,Yasmin Rocha,NaN,A,IA,8.300000,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.500000,True,Ok
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.100000,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.950000,False,Alto risco
26,27,Ana Clara,18.0,A,IA,8.500000,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.750000,True,Ok
27,28,Beatriz Moura,20.0,B,NaN,7.200000,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.400000,True,Ok
28,29,Caio Moreira,19.0,C,Dados,7.032143,NaN,NaN,NaN,NaN,2025-02-22,780.0,Sim,NaN,Ativo,NaN,False,Ok
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.400000,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo,8.650000,True,Ok

## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

In [ ]:
df = df.sort_values(by='media', ascending=False)

In [83]:
df['curso'].value_counts()

curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64

In [87]:
df.groupby('curso')['nota1'].mean()

curso
Dados              7.703214
Desenvolvimento    6.600000
IA                 6.721104
Name: nota1, dtype: float64

In [86]:
df.groupby('turma')['faltas'].mean()

turma
A    3.70
B    4.90
C    7.75
Name: faltas, dtype: float64

## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

In [88]:
df.duplicated()

14    False
8     False
23    False
12    False
26    False
0     False
29    False
24    False
6     False
20    False
18    False
4     False
16    False
7     False
27    False
21    False
10    False
1     False
9     False
13    False
15    False
25    False
3     False
19    False
5     False
11    False
22    False
2     False
17    False
28    False
dtype: bool

In [89]:
df_limpo=df.drop_duplicates

In [91]:
df_emails_invalidos = df[
    (~df['email'].str.contains('@', na=False)) |
    (~df['email'].str.contains('.com', na=False))
]
df_emails_invalidos

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
9,10,João Pedro,19.0,A,Desenvolvimento,6.700000,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45,False,Ok
11,12,Lucas Matos,18.0,C,IA,3.500000,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00,False,Alto risco
28,29,Caio Moreira,19.0,C,Dados,7.032143,NaN,NaN,NaN,NaN,2025-02-22,780.0,Sim,NaN,Ativo,NaN,False,Ok

## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

In [92]:
df.to_excel('df_novo.xlsx', index=False)

## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

In [93]:
array_notas = df['nota1'].dropna().to_numpy()

In [94]:
media=np.mean(array_notas)
maior=np.max(array_notas)
menor=np.min(array_notas)
soma=np.sum(array_notas)

In [95]:
array_notas= array_notas+1

In [96]:
notas_maiores_7= array_notas[array_notas>7]

## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

In [ ]:
# Resolva aqui

## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

In [ ]:
# Correção do professor