In [1]:
import pandas as pd

In [5]:
df=pd.read_excel('database.xlsx')

df.head(10)

,id_produto,categoria,produto,variante,unidade_venda,quantidade_minima,limite_sabores,preco,unidade_preco,observacoes
0,P001,Mini Cupcakes,Mini Cupcake,Tradicional,unidade,12.0,até 2 sabores,4,cada,Sem sainha. Recheio e cobertura à escolha.
1,P002,Mini Cupcakes,Mini Cupcake,Especial,unidade,12.0,até 2 sabores,5,cada,Com sainhas e tags no tema. Recheio e cobertur...
2,P003,Cupcakes,Cupcake,Tradicional,unidade,10.0,não informado,8,cada,Recheio e cobertura à escolha. Embalagem de pr...
3,P004,Cupcakes,Cupcake,Especial,unidade,10.0,não informado,9,cada,Recheio e cobertura à escolha. Embalagem de pr...
4,P005,Docinhos,Doces Tradicionais,50 unidades,pacote,50.0,1 sabor,110,pacote,20g; decoração com granulados comuns; confeito...
5,P006,Docinhos,Doces Tradicionais,100 unidades,pacote,100.0,até 2 sabores,200,pacote,20g; decoração com granulados comuns; confeito...
6,P007,Docinhos,Doces Gourmets,50 unidades,pacote,50.0,1 sabor,130,pacote,20g; granulados especiais.
7,P008,Docinhos,Doces Gourmets,100 unidades,pacote,100.0,até 2 sabores,250,pacote,20g; granulados especiais.
8,P009,Docinhos,Doces Especiais,50 unidades,pacote,50.0,1 sabor,140,pacote,20g; sabores especiais.
9,P010,Docinhos,Doces Especiais,100 unidades,pacote,100.0,até 2 sabores,270,pacote,20g; sabores especiais.

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.strip()

df

,id_produto,categoria,produto,variante,unidade_venda,quantidade_minima,limite_sabores,preco,unidade_preco,observacoes
0,P001,Mini Cupcakes,Mini Cupcake,Tradicional,unidade,12.0,até 2 sabores,4,cada,Sem sainha. Recheio e cobertura à escolha.
1,P002,Mini Cupcakes,Mini Cupcake,Especial,unidade,12.0,até 2 sabores,5,cada,Com sainhas e tags no tema. Recheio e cobertur...
2,P003,Cupcakes,Cupcake,Tradicional,unidade,10.0,não informado,8,cada,Recheio e cobertura à escolha. Embalagem de pr...
3,P004,Cupcakes,Cupcake,Especial,unidade,10.0,não informado,9,cada,Recheio e cobertura à escolha. Embalagem de pr...
4,P005,Docinhos,Doces Tradicionais,50 unidades,pacote,50.0,1 sabor,110,pacote,20g; decoração com granulados comuns; confeito...
5,P006,Docinhos,Doces Tradicionais,100 unidades,pacote,100.0,até 2 sabores,200,pacote,20g; decoração com granulados comuns; confeito...
6,P007,Docinhos,Doces Gourmets,50 unidades,pacote,50.0,1 sabor,130,pacote,20g; granulados especiais.
7,P008,Docinhos,Doces Gourmets,100 unidades,pacote,100.0,até 2 sabores,250,pacote,20g; granulados especiais.
8,P009,Docinhos,Doces Especiais,50 unidades,pacote,50.0,1 sabor,140,pacote,20g; sabores especiais.
9,P010,Docinhos,Doces Especiais,100 unidades,pacote,100.0,até 2 sabores,270,pacote,20g; sabores especiais.
10,P011,Casquinhas de chocolate,Casquinha,Grupo 1 / 50 unidades,pacote,50.0,não informado,115,pacote,Categoria agrupada a partir do portfólio; conf...
11,P012,Casquinhas de chocolate,Casquinha,Grupo 1 / 100 unidades,pacote,100.0,não informado,220,pacote,Categoria agrupada a partir do portfólio; conf...
12,P013,Casquinhas de chocolate,Casquinha,Grupo 2 / 50 unidades,pacote,50.0,não informado,125,pacote,Categoria agrupada a partir do portfólio; conf...
13,P014,Casquinhas de chocolate,Casquinha,Grupo 2 / 100 unidades,pacote,100.0,não informado,240,pacote,Categoria agrupada a partir do portfólio; conf...
14,P015,Casquinhas de chocolate,Casquinha,Grupo 3 / 50 unidades,pacote,50.0,não informado,135,pacote,Categoria agrupada a partir do portfólio; conf...
15,P016,Casquinhas de chocolate,Casquinha,Grupo 3 / 100 unidades,pacote,100.0,não informado,260,pacote,Categoria agrupada a partir do portfólio; conf...
16,P017,Bombons Trufados,Bombom trufado,Grupo 1 / 50 unidades,pacote,50.0,não informado,150,pacote,Primeiro grupo de sabores listado no portfólio.
17,P018,Bombons Trufados,Bombom trufado,Grupo 1 / 100 unidades,pacote,100.0,não informado,280,pacote,Primeiro grupo de sabores listado no portfólio.
18,P019,Bombons Trufados,Bombom trufado,Grupo 2 / 50 unidades,pacote,50.0,não informado,160,pacote,Segundo grupo de sabores listado no portfólio.
19,P020,Bombons Trufados,Bombom trufado,Grupo 2 / 100 unidades,pacote,100.0,não informado,290,pacote,Segundo grupo de sabores listado no portfólio.
20,P021,Bolos,Bolo,Tradicional - valor por kg,kg,1.0,1 recheio,95,kg,"Sabores tradicionais; para 1kg, usar preço pró..."
21,P022,Bolos,Bolo,Tradicional - somente 1kg,kg,1.0,1 recheio,105,kg,Preço específico para bolo de 1kg.
22,P023,Bolos,Bolo,Tradicional - 2 recheios,kg,1.0,2 recheios,100,kg,Preço por kg com dois recheios diferentes.
23,P024,Bolos,Bolo,Especial - valor por kg,kg,1.0,1 recheio,100,kg,"Sabores especiais; para 1kg, usar preço próprio."
24,P025,Bolos,Bolo,Especial - somente 1kg,kg,1.0,1 recheio,110,kg,Preço específico para bolo de 1kg.
25,P026,Bolos,Bolo,Especial - 2 recheios,kg,1.0,2 recheios,115,kg,Preço por kg com dois recheios diferentes.
26,P027,Bolos,Bolo,Gourmet - valor por kg,kg,1.5,1 recheio,120,kg,Sabores gourmet; informado como somente a part...
27,P028,Bolos,Bolo,Gourmet - somente 1kg,kg,1.0,1 recheio,130,kg,"Preço específico para bolo de 1kg, se aceito p..."
28,P029,Decoração,Adicional cor forte/metalizado,"1,5kg ou 2kg",serviço,1.0,não se aplica,5,adicional,Adicional de decoração por cor forte ou metali...
29,P030,Decoração,Adicional cor forte/metalizado,3kg ou 4kg,serviço,1.0,não se aplica,8,adicional,Adicional de decoração por cor forte ou metali...
30,P031,Decoração,Adicional cor forte/metalizado,5kg,serviço,1.0,não se aplica,12,adicional,Adicional de decoração por cor forte ou metali...
31,P032,Decoração,Bolo com 20cm de altura,Adicional,kg,1.0,não se aplica,5,kg,Adicional de modelo/decoração.
32,P033,Decoração,Naked Cake,Adicional,kg,1.0,não se aplica,10,kg,Adicional de modelo/decoração.